//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class forecast
    {
        public int locationID { get; set; }
        public int ID { get; set; }
        public int temperature { get; set; }
        public int symbolID { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> period { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
