//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.forecasts = new HashSet<forecast>();
        }
    
        public int ID { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    
        public virtual ICollection<forecast> forecasts { get; set; }
    }
}
